export const EventTypes = {
  CHECKIN_EVENT: 'CHECKIN_EVENT',
  CHECKOUT_EVENT: 'CHECKOUT_EVENT',
  PAYMENT_EVENT: 'PAYMENT_EVENT',
  ANOMALY_DETECTED: 'ANOMALY_DETECTED',
  ANOMALY_RESOLVED: 'ANOMALY_RESOLVED'
};
